# Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: domain-analysis-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/timeout: "900s"
        run.googleapis.com/max-scale: "100"
        run.googleapis.com/min-scale: "0"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 900
      containers:
      - image: gcr.io/PROJECT_ID/domain-analysis-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GCP_PROJECT_ID
          value: "PROJECT_ID"
        - name: BIGQUERY_DATASET_ID
          value: "domain_intelligence"
        - name: BIGQUERY_TABLE_ID  
          value: "domain_analysis"
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: SERPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: serper-api-key
        - name: BRIGHTDATA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: brightdata-token
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: google-api-key
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10